CREATE TABLE `sys_user` (
  `id` bigint NOT NULL COMMENT 'ID',
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '账号',
  `password` varchar(128) NOT NULL COMMENT '密码',
  `code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '工号',
  `name` varchar(64) NOT NULL COMMENT '名称',
  `dept_id` bigint NOT NULL COMMENT '部门ID',
  `post_rank_id` bigint DEFAULT NULL COMMENT '职级ID',
  `mobile` varchar(32) NOT NULL COMMENT '手机号',
  `email` varchar(128) DEFAULT '' COMMENT '邮箱',
  `sex` tinyint(1) DEFAULT NULL COMMENT '性别（1：男，0：女）',
  `birthday` date DEFAULT NULL COMMENT '生日',
  `id_card_no` varchar(32) DEFAULT '' COMMENT '身份证号码',
  `entry_date` date NOT NULL COMMENT '入职日期',
  `expiration_date` date DEFAULT NULL COMMENT '有效期',
  `avatar_file_id` bigint DEFAULT NULL COMMENT '图像文件ID',
  `introduction` varchar(255) DEFAULT '' COMMENT '简介',
  `emp_status` smallint NOT NULL DEFAULT '1' COMMENT '在职状态 1:在职,2:离职）',
  `status` smallint NOT NULL DEFAULT '1' COMMENT '账号状态（1：正常，0：停用）',
  `create_type` smallint NOT NULL COMMENT '创建方式 1:管理后台,2:同步',
  `create_by` bigint NOT NULL COMMENT '创建人ID',
  `create_by_name` varchar(64) NOT NULL COMMENT '创建人名称',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint NOT NULL COMMENT '更新人ID',
  `update_by_name` varchar(64) NOT NULL COMMENT '更新人名称',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `nick_name` varchar(64) DEFAULT NULL COMMENT '昵称（英文名）',
  `create_dept_id` bigint DEFAULT NULL COMMENT '创建部门ID',
  `security_level` int DEFAULT '2' COMMENT '安全强弱等级 1:弱,2:中,3:强',
  `sync_target_id` varchar(64) DEFAULT '' COMMENT '同步目标ID',
  `sync_target_code` varchar(64) DEFAULT '' COMMENT '同步目标编号',
  `sync_target_type` smallint DEFAULT '0' COMMENT '同步类型 0:自建 1:极兔HR系统',
  `post_name` varchar(255) DEFAULT '' COMMENT '岗位名称',
  `mobile_country` varchar(8) DEFAULT '+86' COMMENT '手机号国家码',
  `entry_day` int DEFAULT NULL COMMENT '入职天数',
  `direct_leader_id` bigint DEFAULT NULL COMMENT '直属上级',
  `is_activate` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否激活 0-否 1-是',
  `activate_time` datetime DEFAULT NULL COMMENT '激活时间',
  `sync_target_leader_id` varchar(64) DEFAULT '' COMMENT '同步目标直属上级ID',
  `sync_target_leader_code` varchar(64) DEFAULT '' COMMENT '同步目标直属上级编号',
  `total_active_all` int NOT NULL DEFAULT '0' COMMENT '总激活人数（全部人员）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_username` (`username`) USING BTREE,
  KEY `uk_sys_user_code` (`code`) USING BTREE,
  KEY `idx_sys_user_dept_id` (`dept_id`) USING BTREE,
  KEY `uk_sys_user_name` (`name`),
  KEY `idx_sys_user_sync_target_code` (`sync_target_code`,`sync_target_type`),
  KEY `idx_sys_user_sync_target_id` (`sync_target_id`,`sync_target_type`),
  KEY `idx_mobile` (`mobile_country`,`mobile`),
  KEY `idx_direct_leader_id` (`direct_leader_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户';